groups:
  - name: ai_companion_alerts
    rules:
      # High Error Rate
      - alert: HighErrorRate
        expr: rate(app_errors_total[5m]) / rate(app_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: ai-companion
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(app_request_duration_seconds_bucket[5m])) > 30
        for: 10m
        labels:
          severity: warning
          service: ai-companion
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (app_memory_usage_bytes / app_memory_limit_bytes) > 0.8
        for: 10m
        labels:
          severity: warning
          service: ai-companion
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # Database Connection Pool Exhaustion
      - alert: DatabasePoolExhaustion
        expr: (db_connections_active / db_connections_max) > 0.9
        for: 5m
        labels:
          severity: critical
          service: ai-companion
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Connection pool utilization is {{ $value | humanizePercentage }}"

      # Low Cache Hit Rate
      - alert: LowCacheHitRate
        expr: cache_hit_rate < 0.7
        for: 15m
        labels:
          severity: warning
          service: ai-companion
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }}"

      # Memory Consolidation Backlog
      - alert: MemoryConsolidationBacklog
        expr: memory_consolidation_backlog > 1000
        for: 30m
        labels:
          severity: warning
          service: ai-companion
        annotations:
          summary: "Memory consolidation backlog high"
          description: "Consolidation backlog has {{ $value }} items"

      # LLM Timeout Rate
      - alert: HighLLMTimeoutRate
        expr: rate(llm_timeouts_total[10m]) / rate(llm_requests_total[10m]) > 0.1
        for: 10m
        labels:
          severity: warning
          service: ai-companion
        annotations:
          summary: "High LLM timeout rate"
          description: "LLM timeout rate is {{ $value | humanizePercentage }}"

  - name: system_alerts
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% on {{ $labels.instance }}"

      # High Memory Usage (System)
      - alert: HighSystemMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 10m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High system memory usage"
          description: "Memory usage is above 90% on {{ $labels.instance }}"

      # High Disk Usage
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes > 0.85
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High disk usage"
          description: "Disk usage is above 85% on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

      # Low Disk Space
      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes / node_filesystem_size_bytes < 0.1
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Low disk space"
          description: "Less than 10% disk space remaining on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

  - name: database_alerts
    rules:
      # Redis Down
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis instance is not responding"

      # High Redis Memory Usage
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 10m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      # PostgreSQL Down
      - alert: PostgreSQLDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL instance is not responding"

      # High PostgreSQL Connection Usage
      - alert: HighPostgreSQLConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 10m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "High PostgreSQL connection usage"
          description: "PostgreSQL connection usage is {{ $value | humanizePercentage }}"

  - name: application_health_alerts
    rules:
      # Application Down
      - alert: ApplicationDown
        expr: up{job="ai-companion-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: ai-companion
        annotations:
          summary: "AI Companion application is down"
          description: "The main application is not responding to health checks"

      # Health Check Failed
      - alert: HealthCheckFailed
        expr: health_check_status != 1
        for: 2m
        labels:
          severity: warning
          service: ai-companion
        annotations:
          summary: "Health check failed"
          description: "Health check {{ $labels.check_name }} is failing"

      # High Request Rate
      - alert: HighRequestRate
        expr: rate(app_requests_total[5m]) > 1000
        for: 10m
        labels:
          severity: warning
          service: ai-companion
        annotations:
          summary: "High request rate"
          description: "Request rate is {{ $value }} requests/second"

  - name: container_alerts
    rules:
      # High Container CPU Usage
      - alert: HighContainerCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: container
        annotations:
          summary: "High container CPU usage"
          description: "Container {{ $labels.name }} CPU usage is above 80%"

      # High Container Memory Usage
      - alert: HighContainerMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.8
        for: 10m
        labels:
          severity: warning
          service: container
        annotations:
          summary: "High container memory usage"
          description: "Container {{ $labels.name }} memory usage is above 80%"

      # Container Restart
      - alert: ContainerRestart
        expr: increase(container_start_time_seconds[1h]) > 1
        for: 0m
        labels:
          severity: warning
          service: container
        annotations:
          summary: "Container restarted"
          description: "Container {{ $labels.name }} has restarted"